name: pulsebreak_plus
description: "A lightweight wellness & habits personal assistant app built with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  font_awesome_flutter: ^10.6.0

  # State management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0

  # Authentication & Social Login
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^5.0.0

  # UI/UX enhancements
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  http: ^1.1.0

  # Additional useful packages for wellness apps
  url_launcher: ^6.2.1        # For external links
  image_picker: ^1.0.4        # For profile pictures
  permission_handler: ^11.0.1 # For handling permissions
  # local_notifications: ^16.3.0 # For wellness reminders

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: TextMeOne
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf
