name: pulsebreak_plus
description: "A lightweight wellness & habits personal assistant app built with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0

  # State management (update if using Riverpod, Bloc, etc.)
  provider: ^6.1.2

  # Firebase Core (you can add other Firebase packages as needed)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0

  # Optional UI/UX enhancements
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/TextMeOne-Regular.ttf
        